#!/bin/bash

usage_exit() {
  cat <<EOS 1>&2
Usage: $0 [-0] [-s] [-f] [-o] [--url] [--title] episode-id
  -0: Aikatsu!
  -s: Aikatsu Stars!
  -f: Aikatsu Friends!
  -o: Aikatsu on parade! 
  -w: Aikatsu on parade! (web anime) (current default)

  --url: Show story url instead of story
  --title: Show story title instead of story
EOS
  exit 1
}

while getopts 0sfohw-: OPT
do
  case $OPT in
    -)
        case "${OPTARG}" in
          url)
              URL=1
              ;;
          title)
              TITLE=1
              ;;
          help)
              usage_exit
              ;;
        esac
        ;;
    0)  MUJIRUSHI=1
        ;;
    s)  STARS=1
        ;;
    f)  FRIENDS=1
        ;;
    o)  ONPARADE=1
        ;;
    o)  ONPARADE_WEB=1
        ;;
    h)  usage_exit
        ;;
    \?) usage_exit
        ;;
  esac
done
shift $((OPTIND - 1))

if [[ -z $MUJIRUSHI && -z $STARS && -z $FRIENDS && -z $ONPARADE && -z $ONPARADE_WEB ]]; then
  # default to ONPARADE_WEB
  ONPARADE_WEB=1
fi


STORY_ID=$1
if [[ -z $STORY_ID ]]; then
  usage_exit
fi

episode_id=`printf %03d $STORY_ID`
series_id=`printf %02d $(( ($STORY_ID - 1)/ 50 + 1))`

if [[ -n $ONPARADE_WEB ]]; then
  # episode_id is formed of 2 digits in onparade_web
  episode_id=`printf %02d $STORY_ID`
  url="http://www.aikatsu.net/webanime/story-${episode_id}.html"
  title_pup_command='.story-main > :nth-child(1) img attr{alt}'
  pup_command='.story-main-frame > :nth-child(2) json{}'
elif [[ -n $ONPARADE ]]; then
  url="http://www.aikatsu.net/story/story-${episode_id}.html"
  title_pup_command='.story-main > :nth-child(1) img attr{alt}'
  pup_command='.story-main-frame > :nth-child(2) json{}'
elif [[ -n $FRIENDS ]]; then
  url="http://www.aikatsu.net/aikatsufriends_${series_id}/story/story-${episode_id}.html"
  title_pup_command='.story-main > :nth-child(1) img attr{alt}'
  if [ $1 -ge 51 ] ; then
    pup_command='.story-main-frame > :nth-child(2) json{}'
  else
    pup_command='.story-waku-menu > :nth-child(2) json{}'
  fi
elif [[ -n $STARS ]]; then
  url="http://www.aikatsu.net/aikatsustars_${series_id}/story/${episode_id}.html"
  title_pup_command='.story-main > :nth-child(1) img attr{alt}'
  if [ $1 -ge 51 ] ; then
    pup_command='.story-text json{}'
  else
    pup_command='.text json{}'
  fi
elif [[ -n $MUJIRUSHI ]]; then
  # MUJIRUSHI series does not organized as groups of 50 episodes
  if [[ $STORY_ID -le 50 ]]; then
    series_id='01'
  elif [[ $STORY_ID -le 101 ]]; then
    series_id='02'
  else
    series_id='03'
  fi
  # URL of MUJIRUSHI series have 2 digit of 0 padding before ep.99
  if [[ $STORY_ID -le 99 ]]; then
    episode_id=`printf %02d $STORY_ID`
  fi
  url="http://www.aikatsu.net/${series_id}/story/${episode_id}.html"

  pup_command='.story-text json{}'
  title_pup_command='#story-main p img attr{alt}'
  # ???????????
  if [[ $STORY_ID -eq 31 ]];then
    pup_command='.story-text3 json{}'
  fi
fi

if [[ -n $URL ]]; then
  echo $url
  exit
fi

if [[ -n $TITLE ]]; then
  curl -s $url | \
    pup "$title_pup_command"
  exit
fi

curl -s $url | \
  pup "$pup_command" | \
  jq --raw-output '.[].text' 
