version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y jq
            go get github.com/ericchiang/pup

      - run:
          name: Test
          command: ./test.sh
