name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  homebrew-release:
    steps:
      - name: Release Homebrew Formula
        if: github.event.release.prerelease != true
        uses: garden-io/update-homebrew-action@v1
        with:
          packageName: 'aikatsu_story'
          templatePath: 'aikatsu_story.rb'
          tapRepo: 'gecko655/homebrew-aikatsu-story'
          srcRepo: 'gecko655/aikatsu-story'
          authToken: ${{ secrets.GITHUB_TOKEN }}
