name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  homebrew-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Homebrew Formula
        if: github.event.release.prerelease != true
        uses: izumin5210/action-homebrew-tap@releases/v0
        with:
          tap: izumin5210/homebrew-tools
          token: ${{ secrets.GITHUB_TOKEN }}
          tap-token: ${{ secrets.GITHUB_TOKEN }}
